export const WO_COLUMNS = [
  "WO_Number",
  "WO_Line",
  "Customer",
  "Account_ID",
  "Patient_Name",
  "Labeling",
  "MFG",
  "Customer_PO",
  "Shopping_Cart",
  "ShipTo_Addr_BillTo",
  // "Order_ID",
  // "Reference_ID",
  "Side",
  "Eye",
  "Type_Code",
  "cldfile",
  // "Lens_Type_Laser",
  "Color",
  "BC1_BC2",
  "Cylinder",
  "PW1_PW2",
  "ADD",
  "DIAM",
  "CD_CN",
  "OZ1_OZ2",
  "AXIS",
  "SAG_HEIGHT",
  "RC1_value",
  "RC1_width",
  "RC1_cyl",
  "AC1_value",
  "AC1_width",
  "AC1_cyl",
  "AC2_value",
  "AC2_width",
  "AC2_cyl",
  "AC3_value",
  "AC3_width",
  "AC3_cyl",
  "PC1_value",
  "PC1_width",
  "CT_width",
  "Queue_Thickness",
  "mtnum",
  "ctnum",
];

export const WO_COLUMNS_EXCEL = [
  "Patient Name",
  "PO",
  "No.",
  "OD/OS",
  "K-Code",
  "P-Code",
  "SPEC",
  "Cyl",
  "Diam",
  "Color",
  "Qty",
  "Laser",
  "Design",
  "Viet Label",
  "Labeling",
  "Ship Code",
  "Previous S.O#",
  "Note",
  "Device",
  "Mfg",
  "Mat_Code",
  "Mat_Lot",
  "GTIN",
  "Bill_To",
  "Ship_To",
  "Type",
  "Cyl_p",
  "PC1_Radius",
  "PC2_Radius",
  "Edge_Thick",
  "Center_Thick",
];
// 2) Expected columns (display names for messages)
export const EXPECTED_REQUIRED = [
  "Patient Name",
  "PO",
  "No.",
  "OD/OS",
  "K-Code",
  "P-Code",
  "SPEC",
  "Cyl",
  "Diam",
  "Color",
  "Qty",
  "Laser",
  "Design",
  "Viet Label",
  "Labeling",
  "Ship Code",
  "Previous S.O#",
  // previously added required
  "Mat_Lot",
  "Bill_To",
  "Ship_To",
  "Device",
  "Mfg",
  "Mat_Code",
  "GTIN",
  "Type",
  "Cyl_p",
  "PC1_Radius",
  "PC2_Radius",
  "Edge_Thick",
  "Center_Thick",
];

export const EXPECTED_OPTIONAL = [
  "Note", // new optional column
];

// export const SHEET_NAME = "WorkOrders"; // <— your single tab

export const SHEET_NAME_TAB = "clo"; // <— your single tab
