export const WO_COLUMNS = [
  "woNumber",
  "patientName",
  "po",
  "poDate",
  "batchNo",
  "no",
  "odOs",
  "kCode",
  "pCode",
  "priceCode",
  "spec",
  "cylToric",
  "diam",
  "color",
  "laser",
  "design",
  "vietLabel",
  "labeling",
  "shipCode",
  "previousSO",
  "note",
  "device",
  "mfg",
  "matCode",
  "matLot",
  "gtin",
  "soldTo",
  "billTo",
  "cldfile",
  "type",
  "cylValue",
  "edgeThick",
  "centerThick",
  "eValue",
  "containerCode",
  "bc1",
  "bc2",
  "pw1",
  "pw2",
  "oz1",
  "oz2",
  "rc1Radius",
  "ac1Radius",
  "ac2Radius",
  "ac3Radius",
  "rc1Tor",
  "ac1Tor",
  "ac2Tor",
  "ac3Tor",
  "rc1Width",
  "ac1Width",
  "ac2Width",
  "ac3Width",
  "pc1Radius",
  "pc2Radius",
  "pcwidth",
];

export const WO_COLUMNS_EXCEL = [
  "Patient Name",
  "PO",
  "PO date",
  "No.",
  "OD/OS",
  "K-Code",
  "P-Code",
  "SPEC",
  "Cyl",
  "Diam",
  "Color",
  "Qty",
  "Laser",
  "Design",
  "Viet Label",
  "Labeling",
  "Ship Code",
  "Previous S.O#",
  "Note",
  "Device",
  "Mfg",
  "Mat_Code",
  "Mat_Lot",
  "GTIN",
  "Sold_To",
  "Bill_To",
  "cldfile",
  "Type",
  "Cyl_p",
  "PC1_Radius",
  "PC2_Radius",
  "Edge_Thick",
  "Center_Thick",
  "eValue",
  "Container Code",
];
// 2) Expected columns (display names for messages)
export const EXPECTED_REQUIRED = [
  "Patient Name",
  "PO",
  "PO date",
  "No.",
  "OD/OS",
  "K-Code",
  "P-Code",
  "SPEC",
  "Cyl",
  "Diam",
  "Color",
  "Qty",
  "Laser",
  "Design",
  "Viet Label",
  "Labeling",
  "Ship Code",
  "Previous S.O#",
  // previously added required
  "Mat_Lot",
  "Sold_To",
  "Bill_To",
  "cldfile",
  "Device",
  "Mfg",
  "Mat_Code",
  "GTIN",
  "Type",
  "Cyl_p",
  "PC1_Radius",
  "PC2_Radius",
  "Edge_Thick",
  "Center_Thick",
  "eValue",
  "Container Code",
];

export const EXPECTED_OPTIONAL = [
  "Note", // new optional column
];

// export const SHEET_NAME = "WorkOrders"; // <— your single tab

export const SHEET_NAME_TAB = "clo"; // <— your single tab

// Column display names for grid headers
export const COLUMN_DISPLAY_NAMES = {
  woNumber: "WO Number",
  patientName: "Patient Name",
  po: "PO",
  poDate: "PO Date",
  batchNo: "Batch No",
  no: "No.",
  odOs: "OD/OS",
  kCode: "K-Code",
  pCode: "P-Code",
  spec: "SPEC",
  cyl: "Cyl",
  diam: "Diam",
  color: "Color",
  laser: "Laser",
  design: "Design",
  vietLabel: "Viet Label",
  labeling: "Labeling",
  shipCode: "Ship Code",
  previousSO: "Previous S.O#",
  note: "Note",
  device: "Device",
  mfg: "Mfg",
  matCode: "Mat Code",
  matLot: "Mat Lot",
  gtin: "GTIN",
  soldTo: "Sold To",
  billTo: "Bill To",
  cldfile: "CLD File",
  type: "Type",
  cylP: "Cyl P",
  edgeThick: "Edge Thick",
  centerThick: "Center Thick",
  eValue: "E-Value",
  containerCode: "Container Code",
  bc1: "BC1",
  bc2: "BC2",
  pw1: "PW1",
  pw2: "PW2",
  oz1: "OZ1",
  oz2: "OZ2",
  rc1Radius: "RC1 Radius",
  ac1Radius: "AC1 Radius",
  ac2Radius: "AC2 Radius",
  ac3Radius: "AC3 Radius",
  rc1Tor: "RC1 Tor",
  ac1Tor: "AC1 Tor",
  ac2Tor: "AC2 Tor",
  ac3Tor: "AC3 Tor",
  rc1Width: "RC1 Width",
  ac1Width: "AC1 Width",
  ac2Width: "AC2 Width",
  ac3Width: "AC3 Width",
  pc1Radius: "PC1 Radius",
  pc2Radius: "PC2 Radius",
  pcwidth: "PC Width",
};
